### ISSUE TITLE
top level links

### ISSUE THREAD

**Issue by yn-coder** [convergenceIM/alpha-scientist#10]
How can I add another top level link? I'm considering adding an "About" and a "Services" item up top. Should probably also have a "blog" link up to because it's not obvious how to get back there if in the about page

**Comment by yn-coder** [comment]
Looks like doesn't respect `MENUITEMS` settings

http://docs.getpelican.com/en/stable/settings.html#MENUITEMS

**Comment by convergenceIM** [comment]
Closing.  Should not be relevant w/ new theme
