### ISSUE TITLE
Tweaking the format of themes

### ISSUE THREAD

**Issue by convergenceIM** [convergenceIM/alpha-scientist#12]
There are lots of small things which I'd like to change.  For instance, I'd like to make the color of the blog title match to the logo, actually maybe change the color theme of the full blog to be more very dark blue than black.  

I'd also like to change the font of the sub-title ("Using data science...") to be italicized and somewhat larger (not as big as the title itself).  

I'm always glad for help but need to learn how to do little things myself.  Do I change the templates\index.html file?  I feel like if I change docs\index.html it'll keep getting overwritten.  

Is there an easy tool for WYSIWYG adjusting these sorts of things - or a cheat sheet for how to directly modify the HTML?  I don't know it but am sure it's not that hard to do the basics

**Comment by yn-coder** [comment]
I think the first step is to try to modify the template jtml's, placed here 

    alpha-scientist / themes / pelican-alchemy / alchemy / templates / 

If this a plain html, you can try to customize it,

**Comment by convergenceIM** [comment]
Let's hold off on this until the octopress template

**Comment by convergenceIM** [comment]
Closing for now...
