### ISSUE TITLE
slug is an url, not a caption

### ISSUE THREAD

**Issue by yn-coder** [convergenceIM/alpha-scientist#14]

**Comment by yn-coder** [comment]
slug is an url, not a caption

You should'n set it like this
    
    Slug: A unique framework for combining the outputs of multiple machine learning prediction models

It shoild be like this
  
    Slug: a_unique_framework

**Comment by convergenceIM** [comment]
got it, thanks.

**Comment by yn-coder** [comment]
Close it?

**Comment by convergenceIM** [comment]
Closing.
