### ISSUE TITLE
Making notebooks downloadable

### ISSUE THREAD

**Issue by convergenceIM** [convergenceIM/alpha-scientist#16]
Is it possible to make the source notebooks downloadable by site visitors (ideally with a link within the post itself)?  It'd be a convenience for readers to be able to replicate the code w/o copy-paste.

**Comment by yn-coder** [comment]
Is link to github repo are enough? If now - then we need to copy the notebook to docs folder too.

**Comment by convergenceIM** [comment]
I think that'll be fine.  Ideally, a link to the individual file would be
slightly better.  I wish github provided executable jupyter notebook
environments rather than just nbviewer displays.  It's a low priority thing
- just trying to be easy to replicate


*    Chad Gray, CFA*
*    Portfolio Manager & Managing Director*
    *415.967.3257*

    cgray@convergence-investments.com

*    www.convergence-investments.com
<http://www.convergence-investments.com>*

                   <https://www.linkedin.com/in/chadgraycfa>
<https://twitter.com/ConvergenceIM>
Services offered through Convergence Investment Management, LLC, a
California Registered Investment Adviser (CRD #167193). No information
presented should be used or considered as an offer to sell or a
solicitation of an offer to buy any interest in any investment fund. Any
such offer or solicitation can and will be made only by means of the
confidential offering memorandum of each such investment fund, and only in
jurisdictions in which such an offer would be lawful and only to
individuals who meet the investor suitability and sophistication
requirements of each such investment fund.

This message and any attachments contain information which may be
confidential and/or privileged and is intended for use only by the
addressee(s) named on this transmission. If you are not the intended
recipient, or the employee or agent responsible for delivering the message
to the intended recipient, you are notified that any review, copying,
distribution or use of this transmission is strictly prohibited. If you
have received this transmission in error, please (i) notify the sender
immediately by e-mail or by telephone and (ii) destroy all copies of this
message.

**Comment by yn-coder** [comment]
Add to page something like this

    [Download](https://github.com/convergenceIM/alpha-scientist/blob/master/content/01_Data_management.ipynb)

Example output:

[Download](https://github.com/convergenceIM/alpha-scientist/blob/master/content/01_Data_management.ipynb)

**Comment by convergenceIM** [comment]
![button_ipynb-notebook](https://user-images.githubusercontent.com/22535225/42860543-ee33636e-8a0b-11e8-987a-c6e1413b945f.png)


Looks nice.  I've added a button to sell-in-may with the link.  Works best if reader rigth clicks and "save link as" so it downloads as an ipynb rather than html file
