### ISSUE TITLE
How to link to other posts

### ISSUE THREAD

**Issue by convergenceIM** [convergenceIM/alpha-scientist#18]
What's the syntax to hyperlink to another one of the blog posts within jupyter markdown?  I think you did this for me before publishing the first time and am not sure if you did directly within the html files or if pelican is smart enough to create the correct relative links to the ----.html files

**Comment by yn-coder** [comment]
i think you can try simple Jupyter link to the notebook `slug`, or may be `slug.html`

**Comment by yn-coder** [comment]
I've checked it.

If you insert the following text in markdown cell of your notebook

    Link to [Notebook title](02_Feature_Engineering.ipynb)

it will be a correct notebook link in your Jupyter edit/view mode.

**But `pelican-ipynb` doesn't proceeded it, so doesn't do like this**.

So you need to add the ordinar href link to html fiile, like this

    [Notebook title](ensemble_modeling.html)

where `ensemble_modeling.html` is a resulting html file

**Comment by convergenceIM** [comment]
Thanks I'll try that next time I publish


*    Chad Gray, CFA*
*    Portfolio Manager & Managing Director*
    *415.967.3257*

    cgray@convergence-investments.com

*    www.convergence-investments.com
<http://www.convergence-investments.com>*

                   <https://www.linkedin.com/in/chadgraycfa>
<https://twitter.com/ConvergenceIM>
Services offered through Convergence Investment Management, LLC, a
California Registered Investment Adviser (CRD #167193). No information
presented should be used or considered as an offer to sell or a
solicitation of an offer to buy any interest in any investment fund. Any
such offer or solicitation can and will be made only by means of the
confidential offering memorandum of each such investment fund, and only in
jurisdictions in which such an offer would be lawful and only to
individuals who meet the investor suitability and sophistication
requirements of each such investment fund.

This message and any attachments contain information which may be
confidential and/or privileged and is intended for use only by the
addressee(s) named on this transmission. If you are not the intended
recipient, or the employee or agent responsible for delivering the message
to the intended recipient, you are notified that any review, copying,
distribution or use of this transmission is strictly prohibited. If you
have received this transmission in error, please (i) notify the sender
immediately by e-mail or by telephone and (ii) destroy all copies of this
message.

**Comment by convergenceIM** [comment]
Works, closing
