### ISSUE TITLE
Disqus comments aren't appearing

### ISSUE THREAD

**Issue by yn-coder** [convergenceIM/alpha-scientist#19]

**Comment by yn-coder** [comment]
This is because

    {% if (DISQUS_SITENAME or ISSO_SITEURL) and SITEURL and article.status != "draft" %}

**Comment by yn-coder** [comment]
Disqus is back

![disqus](https://user-images.githubusercontent.com/8451944/42412286-0d9aee9a-8212-11e8-804a-8dddfc6b1ccc.png)

**Comment by yn-coder** [comment]
I've set the following in `pelicanconf.py`

SITEURL = 'https://alphascientist.com'
RELATIVE_URLS = True

Now we have siye url, but relative paths (in html refs) doesn't break the links in case of the local development

**Comment by convergenceIM** [comment]
OK, confirmed that disqus is working for me too.  Keeping this open until I make sure my pelicanconf file has the same lines

**Comment by yn-coder** [comment]
Do `git pull` to take all my changes. Do you work with cli, or some GUI, like smartgit ?

**Comment by convergenceIM** [comment]
OK, will do.  I usually use the git integration in PyCharm

**Comment by convergenceIM** [comment]
Disqus stopped loading.  Was working yesterday.  Today it isnt.  Can you confirm on your end?  I've tried two browsers on one machine

We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.

**Comment by yn-coder** [comment]
Yes, broking

**Comment by yn-coder** [comment]
Working here

https://alphascientist.com/ML_data_management.html

Doesn't working here

https://alphascientist.com/feature_engineering.html

**Comment by yn-coder** [comment]
Can't find the difference. Can you see something in disqus admin cp ?

**Comment by convergenceIM** [comment]
Nothing on the admin panel.  Two possibilities:
1) The first blog post makes use of a custom CSS template (formatting tables) which I plan to do to others.  Can't imagine this would affect disqus though
2) I had made a dummy comment on part 1, then deleted it.  Wonder if that helps it to "remember" that page's IP?  

> The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/.

**Comment by yn-coder** [comment]
Thus could explain #26

**Comment by yn-coder** [comment]
If GHP IP's is changed, you'll need to update your dns

**Comment by convergenceIM** [comment]
Seems to be working again. I republished from my workstation.  Also, I pushed the pelicanconf and publishconf files so if you do any work on them, pls pull them first so we don't get forked

**Comment by yn-coder** [comment]
Is https problem solved? Do you change something in dns?

**Comment by convergenceIM** [comment]
Works.  Not sure why.  I did a bunch of things to try to clean up the settings but mostly I think I republished and it worked immediatly
