### ISSUE TITLE
Social links aren't appearing (does the pelicanconf/publishconf file you're using contain the social links?)

### ISSUE THREAD

**Issue by yn-coder** [convergenceIM/alpha-scientist#20]

**Comment by yn-coder** [comment]
Your previous social links stay laying in the `pelicanconf_.py` (with `_` )

    # Social widget
    SOCIAL = (('Linkedin', 'https://www.linkedin.com/in/chadgraycfa/'),
              ('Twitter', 'https://twitter.com/data2alpha'),)

Going to rescue!

**Comment by yn-coder** [comment]
done

![the alpha scientist - mozilla firefox_2018-07-07_18-29-07](https://user-images.githubusercontent.com/8451944/42412360-b8a5b8f0-8213-11e8-804a-67f7c22d9209.png)

**Comment by convergenceIM** [comment]
Works.  Closing
