### ISSUE TITLE
"About" tab next. Add another non-blog page ("Consulting")

### ISSUE THREAD

**Issue by yn-coder** [convergenceIM/alpha-scientist#21]
Need to add an "About" tab next to the Blog tab on the menu bar.  I may also want to add another non-blog page ("Consulting").

**Comment by yn-coder** [comment]
`DISPLAY_PAGES_ON_MENU` should work, but they don't

Checking

**Comment by convergenceIM** [comment]
This is great.  What's your recommendation for how to create/edit the HTML for these pages?  Just a one cell ipynb named about.ipynb etc... Use an HTML editor of some sort?

**Comment by yn-coder** [comment]
pages could by `.ipynb` or '.md'. Right now it's `.md` files here https://github.com/convergenceIM/alpha-scientist/tree/master/content/pages

MD it's just a plain text, Formatting is just **equal as _github_ comments**.

**Comment by convergenceIM** [comment]
Works.  Closing
