### ISSUE TITLE
twitter

### ISSUE THREAD

**Issue by yn-coder** [convergenceIM/alpha-scientist#22]
want to embed the twitter feed in the right sidebar (the [docs](https://github.com/duilio/pelican-octopress-theme/blob/master/README.rst) make it look like they've already built this functionality into the theme

**Comment by yn-coder** [comment]
need for

    TWITTER_WIDGET_ID: (required to enable feed) ID obtained from twitter settings

**Comment by convergenceIM** [comment]
perhaps it's twsrc%5Etfw?

**Comment by yn-coder** [comment]
I'll try.

**Comment by yn-coder** [comment]
No, doesn't work with `twsrc%5Etfw` or such. I've placed the feed block into, but is'a bad way.

To use the octopress settings we need the ID from here

https://twitter.com/settings/widgets

![tag tutorial the alpha scientist - google chrome_2018-07-12_07-47-57](https://user-images.githubusercontent.com/8451944/42613139-f6a353be-85a7-11e8-8712-1ddb095f792c.png)

**Comment by yn-coder** [comment]
Your tweets are here, but whithout ID it's loading badge is visible

![the alpha scientist - google chrome_2018-07-13_21-47-48](https://user-images.githubusercontent.com/8451944/42708654-971e1312-86e6-11e8-9838-a7d5edb9dbbc.png)

**Comment by convergenceIM** [comment]
I think that's good.
