### ISSUE TITLE
locale

### ISSUE THREAD

**Issue by yn-coder** [convergenceIM/alpha-scientist#25]
![tag tutorial the alpha scientist - google chrome_2018-07-08_22-56-31](https://user-images.githubusercontent.com/8451944/42423414-4e301660-8302-11e8-9623-46bc81a40f7f.png)

**Comment by yn-coder** [comment]
now EN

![the alpha scientist - google chrome_2018-07-08_23-05-19](https://user-images.githubusercontent.com/8451944/42423472-7391e450-8303-11e8-92b5-9ff42e604735.png)

**Comment by convergenceIM** [comment]
Excellent

**Comment by yn-coder** [comment]
done
