### ISSUE TITLE
HTTPS Failure

### ISSUE THREAD

**Issue by convergenceIM** [convergenceIM/alpha-scientist#26]
Same odd behavior is happening where I'm getting a privacy error when connecting in chrome browser.  Works fine in explorer or firefox.

**Comment by convergenceIM** [comment]
Getting similar errors in other browsers now...

> Your connection is not secure
> 
> The owner of alphascientist.com has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.
> 
> This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox only connect to it securely. As a result, it is not possible to add an exception for this certificate.

**Comment by convergenceIM** [comment]
I've just tried removing the force https option to see if that makes these problems go away.

**Comment by yn-coder** [comment]
Check show it's all right.

https://www.sslshopper.com/ssl-checker.html#hostname=alphascientist.com

**Comment by convergenceIM** [comment]
Has worked for me since I created the bug, so will close for now
