### ISSUE TITLE
Re-order the posts

### ISSUE THREAD

**Issue by yn-coder** [convergenceIM/alpha-scientist#3]
> I'll need to re-order the posts, assume that's easily done by changing the meta-info files?

**Comment by yn-coder** [comment]
@convergenceIM Ordering depends on blog article data. Just edit the `Date` value

**Comment by yn-coder** [comment]
Is ordering works?

**Comment by convergenceIM** [comment]
Yes, and I understand how to tweak the dates to make them so.
