### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by convergenceIM** [convergenceIM/alpha-scientist#32]
I am being asked to enable RSS feed (or atom or feedburner).  The only one I can see in the theme docs is feedburner
https://github.com/duilio/pelican-octopress-theme

the general pelican docs have support for all.  
http://docs.getpelican.com/en/stable/settings.html#feed-settings

I don't know which is better for my needs, whatever is easiest/best

**Comment by yn-coder** [comment]
To integrate with feedburner you need to generate the feed xml in any way

**Comment by yn-coder** [comment]
![the alpha scientist - google chrome_2018-07-14_12-35-24](https://user-images.githubusercontent.com/8451944/42723209-7590eec8-8762-11e8-9ed6-3226e99986ab.png)

**Comment by yn-coder** [comment]
Now we could go further.

**Comment by convergenceIM** [comment]
This is great.  I think that's sufficient.  Closing
