### ISSUE TITLE
Some html files is missing

### ISSUE THREAD

**Issue by yn-coder** [convergenceIM/alpha-scientist#33]
Some html files is missing

![page not found github pages - google chrome_2018-07-14_12-38-38](https://user-images.githubusercontent.com/8451944/42723233-e5746cd8-8762-11e8-89b0-6fd849c04a69.png)

![alpha-scientistdocstag at master convergenceimalpha-scientist - google chro_2018-07-14_12-38-49](https://user-images.githubusercontent.com/8451944/42723234-ea03d586-8762-11e8-9629-5dc5af9ca59b.png)

You need to commit it
* spy.html
* market-anomaly.html
* seasonality.html

**Comment by yn-coder** [comment]
All's good except https://alphascientist.com/tag/seasonality.html

**Comment by yn-coder** [comment]
Now working. I don't nowwhat it was - re push the file and now all's done. May be some GHP gap?

**Comment by convergenceIM** [comment]
I hadn't explicitly added the new HTMLs which were created when I made new tabs (a new html is created to index the articles with that tag each time a new tag is used).  

Re-pushed with those added

**Comment by convergenceIM** [comment]
closing
