### ISSUE TITLE
About

### ISSUE THREAD

**Issue by yn-coder** [convergenceIM/alpha-scientist#37]
> do something to fix the formatting of the About page, which still looks bad. Maybe I can just remove the quote block and go back to bullets which extend beyond the text to the left.

**Comment by yn-coder** [comment]
![about the alpha scientist - mozilla firefox_2018-10-09_22-29-37](https://user-images.githubusercontent.com/8451944/46693594-f6639880-cc12-11e8-95a9-91b17c979724.png)

**Comment by yn-coder** [comment]
![about the alpha scientist - mozilla firefox_2018-10-09_22-31-39](https://user-images.githubusercontent.com/8451944/46693669-290d9100-cc13-11e8-87ef-8ea72a2ddd1b.png)

**Comment by yn-coder** [comment]
or

![about the alpha scientist - mozilla firefox_2018-10-10_22-31-38](https://user-images.githubusercontent.com/8451944/46761085-583c0500-ccdc-11e8-9c04-49d75ca4cd84.png)

**Comment by convergenceIM** [comment]
Sorry - I mis-wrote.  I meant about the "consulting" page (with the bullet points, currently appear to be in a quote block.

**Comment by yn-coder** [comment]
So About page is ok?

**Comment by yn-coder** [comment]
#39

**Comment by yn-coder** [comment]
close it
