### ISSUE TITLE
Disqus comment functionality

### ISSUE THREAD

**Issue by yn-coder** [convergenceIM/alpha-scientist#5]
Can you add disqus comment functionality to these?

**Comment by yn-coder** [comment]
Do not working on site. Checking.

**Comment by yn-coder** [comment]
Could you please check for this manual ?

https://help.disqus.com/troubleshooting/im-receiving-the-message-we-were-unable-to-load-disqus

**Comment by yn-coder** [comment]
Disqus is working now, Did you fix it?

**Comment by convergenceIM** [comment]
Did not touch it.


*    Chad Gray, CFA*
*    Portfolio Manager & Managing Director*
    *415.967.3257*

    cgray@convergence-investments.com

*    www.convergence-investments.com
<http://www.convergence-investments.com>*

                   <https://www.linkedin.com/in/chadgraycfa>
<https://twitter.com/ConvergenceIM>
Services offered through Convergence Investment Management, LLC, a
California Registered Investment Adviser (CRD #167193). No information
presented should be used or considered as an offer to sell or a
solicitation of an offer to buy any interest in any investment fund. Any
such offer or solicitation can and will be made only by means of the
confidential offering memorandum of each such investment fund, and only in
jurisdictions in which such an offer would be lawful and only to
individuals who meet the investor suitability and sophistication
requirements of each such investment fund.

This message and any attachments contain information which may be
confidential and/or privileged and is intended for use only by the
addressee(s) named on this transmission. If you are not the intended
recipient, or the employee or agent responsible for delivering the message
to the intended recipient, you are notified that any review, copying,
distribution or use of this transmission is strictly prohibited. If you
have received this transmission in error, please (i) notify the sender
immediately by e-mail or by telephone and (ii) destroy all copies of this
message.

**Comment by yn-coder** [comment]
Ok. Disqus is working now.
