### ISSUE TITLE
How to set up your local env and do update your blog

### ISSUE THREAD

**Issue by yn-coder** [convergenceIM/alpha-scientist#7]
## How to set up your local env 

1. Create the python virtual env at your local machine
2. Pip install the Jupyter and Pelican in your virtual env
3. Clone this repo direct as subfolder to your virtual env. This give the ability to run Jupyter and Pelican debug tasks from one place, and use the `git diff` to control the changes

## How to update your blog

1. Edit articles in `content` folder, pages in `content\pages` folder.
2. Put the images to `content\images` folder and it subfolders
3. Run `pelican content` command to rebuild the `docs` output
4. Run `python -m pelican.server` command to start local https server to see `http://localhost:8000/` debug host (server reloads the `docs` authomatically)
5. Commit and push all local changes (both `content` and `docs` folders) to GitHub
6. Refresh your site to see the changes

**Comment by convergenceIM** [comment]
Closing
