### ISSUE TITLE
suppress the author name (and folder, if possible)

### ISSUE THREAD

**Issue by yn-coder** [convergenceIM/alpha-scientist#8]
suppress the author name (and folder, if possible)

https://github.com/nairobilug/pelican-alchemy/wiki/Settings#hide_authors

**Comment by yn-coder** [comment]
@convergenceIM Authors is hided. For folders I don't find the settings. May be, with so much (#12) issues about themes - it's better to lok for more comfortable theme ?

**Comment by convergenceIM** [comment]
Agreed. I assume it’s easy to swap themes and see how they look? Perhaps you could outline the steps for me and I could try several. 

Also I was successful in building the HTML locally

**Comment by yn-coder** [comment]
To choose a new theme - just place the static to `themes` folder and edit the line in `pelicanconf.py` https://github.com/convergenceIM/alpha-scientist/blob/master/pelicanconf.py#L43, then rebuild.

There is a lot of themes here
http://www.pelicanthemes.com/
https://github.com/getpelican/pelican-themes

**Comment by convergenceIM** [comment]
Understand the process for this.  Closing so any issues related to the new theme can be tracked in a different issue
